language: ruby
cache: bundler
rvm:
- 2.6.3
before_install:
- gem install -v 2.0.2 bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
- bundle exec rake db:schema:load
services:
- postgresql
_shared_addons: &shared_addons
  hosts:
    - localmumuki.io
    - test.localmumuki.io
    - the-public-org.localmumuki.io
    - private.localmumuki.io
jobs:
  include:
    # All Ruby tests, including Capybara with default driver
    - script: bundle exec rake

    # Capybara and Teaspoon tests on Chrome
    - script:
        - bundle exec rake capybara
        - bundle exec rake teaspoon
      addons:
        <<: *shared_addons
        chrome: stable
        apt:
          packages:
            - chromium-chromedriver
      env: MUMUKI_CAPYBARA_DRIVER=selenium_chrome_headless
      before_install:
        - gem install -v 2.0.2 bundler
        - ln -s /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"

    # Capybara and Teaspoon tests on Firefox
    - script:
        - bundle exec rake capybara
        - bundle exec rake teaspoon
      addons:
        <<: *shared_addons
        firefox: '79.0'
      env: MUMUKI_CAPYBARA_DRIVER=selenium_headless MOZ_HEADLESS=1
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
        - bundle exec rake db:schema:load
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
        - mkdir geckodriver && tar -xzf geckodriver-v0.27.0-linux64.tar.gz -C geckodriver && rm geckodriver-v0.27.0-linux64.tar.gz
        - export PATH=$PATH:$PWD/geckodriver
deploy:
  - provider: rubygems
    api_key:
      secure: Xtu9wRywQXA+J+hhunUC8vUpbXZRJac06dFuEcb7QDmr19Fzrik92vlGTWn17VMIMGLQ5NJhjwfgjWgNJKD6EZbWMx+iwkADvPBJsBGD5AV9A9Tw1SnoiSaXfGH6KqlvPd8HlRWrL49ZUKkMpMhsvQHp3z/qcKM/PUpbcE+nC44=
    gem: mumuki-laboratory
    gemspec: mumuki-laboratory.gemspec
    on:
      tags: true
      repo: mumuki/mumuki-laboratory
