language: ruby
cache:
  bundler: true
  directories:
    - ~/.webdrivers
rvm:
- 2.6.3
env:
  global:
    - WD_CACHE_TIME=0
before_install:
- gem install -v 2.0.2 bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
- bundle exec rake db:schema:load
- export PATH=~/.webdrivers:$PATH
services:
- postgresql
- xvfb
_hosts: &hosts
  hosts:
    - localmumuki.io
    - test.localmumuki.io
    - the-public-org.localmumuki.io
    - private.localmumuki.io
jobs:
  include:
    # All Ruby tests, including Capybara with default driver
    - script: bundle exec rake

    # Capybara and Teaspoon tests on Chrome
    - env: MUMUKI_CAPYBARA_DRIVER=selenium_chrome_headless
      script:
        - bundle exec rake capybara
        - bundle exec rake teaspoon
      addons:
        chrome: stable
        <<: *hosts

    # Capybara and Teaspoon tests on Firefox
    - env: MUMUKI_CAPYBARA_DRIVER=selenium_headless MOZ_HEADLESS=1
      script:
        - bundle exec rake capybara
        - bundle exec rake teaspoon
      addons:
        firefox: '79.0'
        <<: *hosts
deploy:
  - provider: rubygems
    api_key:
      secure: Xtu9wRywQXA+J+hhunUC8vUpbXZRJac06dFuEcb7QDmr19Fzrik92vlGTWn17VMIMGLQ5NJhjwfgjWgNJKD6EZbWMx+iwkADvPBJsBGD5AV9A9Tw1SnoiSaXfGH6KqlvPd8HlRWrL49ZUKkMpMhsvQHp3z/qcKM/PUpbcE+nC44=
    gem: mumuki-laboratory
    gemspec: mumuki-laboratory.gemspec
    on:
      tags: true
      repo: mumuki/mumuki-laboratory
