language: ruby
cache:
  bundler: true
  directories:
    - ~/.webdrivers
rvm:
- 2.6.3
env:
  global:
    - WD_CACHE_TIME=0
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
- bundle exec rake db:schema:load
services:
- postgresql
- xvfb
_hosts: &hosts
  hosts:
    - localmumuki.io
    - base.localmumuki.io
    - central.localmumuki.io
    - empty.localmumuki.io
    - foo.localmumuki.io
    - immersive-orga.localmumuki.io
    - private.localmumuki.io
    - someorga.localmumuki.io
    - test.localmumuki.io
    - the-public-org.localmumuki.io
    - private.localmumuki.io
jobs:
  allow_failures:
    - os: osx
  include:
    # All Ruby tests, including Capybara with default driver
    - script: bundle exec rake

    # Web tests on Chrome
    - env: MUMUKI_SELENIUM_DRIVER=chrome
      script: bundle exec rake spec:web
      addons:
        chrome: stable
        <<: *hosts

    # Web tests on Firefox
    - env: MUMUKI_SELENIUM_DRIVER=firefox
      script: bundle exec rake spec:web
      addons:
        firefox: '79.0'
        <<: *hosts

    # Web tests on Safari
    - env: MUMUKI_SELENIUM_DRIVER=safari RACK_ENV=test RAILS_ENV=test
      os: osx
      osx_image: xcode10.2
      addons:
        postgresql: '10'
        <<: *hosts
      before_install:
        - rm -rf /usr/local/var/postgres
        - initdb /usr/local/var/postgres
        - pg_ctl -D /usr/local/var/postgres start
        - createuser -s postgres
        - sudo /usr/bin/safaridriver --enable
      script: bundle exec rake spec:web
deploy:
  - provider: rubygems
    api_key:
      secure: Xtu9wRywQXA+J+hhunUC8vUpbXZRJac06dFuEcb7QDmr19Fzrik92vlGTWn17VMIMGLQ5NJhjwfgjWgNJKD6EZbWMx+iwkADvPBJsBGD5AV9A9Tw1SnoiSaXfGH6KqlvPd8HlRWrL49ZUKkMpMhsvQHp3z/qcKM/PUpbcE+nC44=
    gem: mumuki-laboratory
    gemspec: mumuki-laboratory.gemspec
    on:
      tags: true
      repo: mumuki/mumuki-laboratory
